version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    env_file:
      - .env
    ports:
      - ${ODOO_PORT}:8069
      - ${ODOO_LONGPOLLING_PORT}:8072
    volumes:
      - data-odoo-pytest-cache:/odoo/.cache
      - ./src/local:/odoo/local-src
      - ./src/addons:/odoo/external-src
      - ./data:/odoo/data
      # to speed build of image customise your .dockerignore (this is an help there)
      # - "./src:/odoo/src/"
    depends_on:
      - db
      - smtp
      - wdb
  nginx:
    image: camptocamp/odoo-nginx:11.0-1.3.0
    platform: linux/x86_64
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - odoo

  db:
    extends:
      file: common.yaml
      service: db
    # ports:
    #   - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgweb:
    image: docker.io/sosedoff/pgweb
    env_file:
      - .env
    ports:
      - 127.0.0.1:${PGWEB_PORT}:8081
    # environment:
    #   PGWEB_DATABASE_URL: postgres://odoo:odoo@db:5432/odoodb?sslmode=disable
    depends_on:
      - db

  smtp:
    extends:
      file: common.yaml
      service: smtpfake
    env_file:
      - .env
    ports:
      - "127.0.0.1:${SMTP_FAKE_WEB_PORT}:8025"
      - "127.0.0.1:${SMTP_FAKE_PORT}:1025"

  wdb:
    image: docker.io/kozea/wdb
    platform: linux/x86_64
    env_file:
      - .env
    ports:
      - "127.0.0.1:${WDB_PORT}:1984"
    # HACK https://github.com/Kozea/wdb/issues/136
    init: true

  kwkhtmltopdf:
    image: ghcr.io/acsone/kwkhtmltopdf:0.12.5-latest
    platform: linux/x86_64

networks:
  default:
    internal: false
  public:

volumes:
  data-odoo:
  data-odoo-pytest-cache:
  db:
